#!/bin/bash

sudo apt update
sudo apt install --yes apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release --codename --short) stable"

sudo apt update
sudo apt install --yes docker-ce docker-ce-cli containerd.io
sudo usermod --append --groups docker vagrant

docker info
