# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  managers = ["manager-1"]
  workers = ["worker-1", "worker-2"]
  names = managers + workers

  names.each.with_index(1) do |name, i|
    config.vm.define "#{name}" do |node|
      node.vm.hostname = "#{name}"
      node.vm.box = "debian/contrib-buster64"
      node.vm.network "private_network", ip: "192.168.165.10#{i}"

      if name == names.last
        node.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "docker-swarm.yml"
          ansible.groups = {
            "managers" => managers,
            "workers" => workers
          }
          ansible.verbose = "-v"
        end
      end
    end
  end
end
